# Generated by Django 5.2.5 on 2025-09-03 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('density', models.FloatField()),
                ('color', models.CharField(max_length=7)),
                ('elements', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geometry_type', models.CharField(max_length=50)),
                ('position', models.JSONField(default=dict)),
                ('rotation', models.JSONField(default=dict)),
                ('scale', models.JSONField(default=dict)),
                ('color', models.CharField(default='#888888', max_length=7)),
                ('opacity', models.FloatField(default=1.0)),
                ('transparent', models.BooleanField(default=False)),
                ('geometry_parameters', models.JSONField(default=dict)),
                ('user_data', models.JSONField(default=dict)),
                ('transform_controls_enabled', models.BooleanField(default=True)),
                ('transform_mode', models.CharField(default='translate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SceneConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_position', models.JSONField(default=dict)),
                ('camera_rotation', models.JSONField(default=dict)),
                ('camera_type', models.CharField(default='perspective', max_length=20)),
                ('camera_fov', models.FloatField(default=75.0)),
                ('camera_near', models.FloatField(default=0.1)),
                ('camera_far', models.FloatField(default=1000.0)),
                ('background_color', models.CharField(default='#262626', max_length=7)),
                ('ambient_light_intensity', models.FloatField(default=1.2)),
                ('directional_light_intensity', models.FloatField(default=3.0)),
                ('grid_size', models.FloatField(default=10.0)),
                ('grid_divisions', models.IntegerField(default=10)),
                ('floor_constraint_enabled', models.BooleanField(default=True)),
                ('floor_level', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SceneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_state', models.JSONField()),
                ('action_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Scene histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spectrum_type', models.CharField(max_length=20)),
                ('multiplier', models.FloatField(default=1.0)),
                ('lines', models.JSONField(default=list)),
                ('isotopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_name', models.CharField(max_length=255)),
                ('volume_type', models.CharField(default='solid', max_length=20)),
                ('real_density', models.FloatField(blank=True, null=True)),
                ('tolerance', models.FloatField(blank=True, null=True)),
                ('is_source', models.BooleanField(default=False)),
                ('gamma_selection_mode', models.CharField(default='by-lines', max_length=20)),
                ('calculation_mode', models.CharField(default='by-lines', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CSGOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=20)),
                ('source_objects', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csg_results', to='projects.geometry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
