# Generated by Django 5.2.5 on 2025-09-03 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geometry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='projects.project'),
        ),
        migrations.AddField(
            model_name='csgoperation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csg_operations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='composition',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='sceneconfiguration',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scene_config', to='projects.project'),
        ),
        migrations.AddField(
            model_name='scenehistory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projects.project'),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra', to='projects.project'),
        ),
        migrations.AddField(
            model_name='volume',
            name='composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.composition'),
        ),
        migrations.AddField(
            model_name='volume',
            name='geometry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volume', to='projects.geometry'),
        ),
        migrations.AddField(
            model_name='volume',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='projects.project'),
        ),
        migrations.AddField(
            model_name='volume',
            name='spectrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.spectrum'),
        ),
    ]
